/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unioeste.sisra.win.tela.fecharConta;

import br.unioeste.sisra.controle.validacao.ContaValidacao;
import br.unioeste.sisra.modelo.to.ContaTO;
import br.unioeste.sisra.win.componente.Handler;
import br.unioeste.sisra.win.listener.IFormulario;
import br.unioeste.sisra.win.listener.OnFormularioResult;
import br.unioeste.sisra.win.tela.funcionario.FuncionarioDialog;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JCLazzarim
 */
public class FecharContaDialog extends javax.swing.JDialog implements IFormulario{

    private final OnFormularioResult listener;
    private final Handler handler;
    boolean novo;
    Long idConta;

    /**
     * Creates new form FuncionarioDialog
     */
    public FecharContaDialog(java.awt.Frame parent, boolean modal, Handler handler, ContaTO conta, OnFormularioResult listener) {
        super(parent, modal);
        this.listener = listener;
        this.handler = handler;
        novo = conta == null;
        initComponents();
        preencherDadosInciais(conta);
        configurarHandler();
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodConta = new javax.swing.JLabel();
        jtxtCodConta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnFinalizarConta = new javax.swing.JButton();
        lblDescricao = new javax.swing.JLabel();
        jtxtDescricao = new javax.swing.JTextField();
        lblAbertura = new javax.swing.JLabel();
        jtxtDataAbertura = new javax.swing.JTextField();
        lblFechamento = new javax.swing.JLabel();
        jtxtDataFechamento = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCodConta.setText("Código conta:");

        jtxtCodConta.setText("jTextField1");
        jtxtCodConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodContaActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnFinalizarConta.setText("Finalizar conta");

        lblDescricao.setText("Descrição:");

        jtxtDescricao.setText("jTextField2");

        lblAbertura.setText("Abertura:");

        jtxtDataAbertura.setText("jTextField3");

        lblFechamento.setText("Fechamento:");

        jtxtDataFechamento.setText("jTextField3");
        jtxtDataFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDataFechamentoActionPerformed(evt);
            }
        });

        lblTotal.setText("Total:");

        jtxtTotal.setText("jTextField5");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCodConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCodConta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDescricao))
                            .addComponent(btnCancelar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(btnFinalizarConta)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtDescricao))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAbertura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFechamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtDataFechamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodConta)
                    .addComponent(jtxtCodConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricao)
                    .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbertura)
                    .addComponent(jtxtDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechamento)
                    .addComponent(jtxtDataFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarConta)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtCodContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodContaActionPerformed

    private void jtxtDataFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDataFechamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDataFechamentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizarConta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtCodConta;
    private javax.swing.JTextField jtxtDataAbertura;
    private javax.swing.JTextField jtxtDataFechamento;
    private javax.swing.JTextField jtxtDescricao;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JLabel lblAbertura;
    private javax.swing.JLabel lblCodConta;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFechamento;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public Object getDados() {
         ContaTO c = new ContaTO();
        if (!novo) {
            c.setId(idConta);
        }
        
        c.setDescricao(jtxtDescricao.getText());
        c.setHoraAbertura(new Date(jtxtDataAbertura.getText()));
        c.setHoraFechamento(new Date(jtxtDataFechamento.getText()));
        c.setTotal(jtxtTotal.getText());
        return c;
    }

    @Override
    public void preencherDadosInciais(Object objeto) {
         if (objeto != null && objeto instanceof ContaTO) {
            ContaTO c = (ContaTO) objeto;
            idConta = c.getId();
            jtxtCodConta.setText(c.getId().toString());
             try {
                 jtxtDataAbertura.setText(c.getHoraAberturaString());
             } catch (Exception ex) {
                 Logger.getLogger(FecharContaDialog.class.getName()).log(Level.SEVERE, null, ex);
             }
            jtxtDescricao.setText(c.getDescricao());
            jtxtTotal.setText(c.getTotal());
        }
    }

    @Override
    public void configurarHandler() {
        handler.add(ContaValidacao.CHAVE_CAMPO_BUSCA, jtxtCodConta);
        handler.add(ContaValidacao.CHAVE_CAMPO_CONTA_ID, jtxtCodConta);
    }
}
