/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unioeste.sisra.win.tela.item;

import br.unioeste.sisra.controle.validacao.ItemValidacao;
import br.unioeste.sisra.modelo.to.ItemTO;
import br.unioeste.sisra.win.componente.Handler;
import br.unioeste.sisra.win.listener.IFormulario;
import br.unioeste.sisra.win.listener.OnFormularioResult;

/**
 *
 * @author Mauriverti
 */
public final class ItemDialog extends javax.swing.JDialog implements IFormulario {

    private final OnFormularioResult listener;
    private final Handler handler;
    boolean novo;
    Long idItem;

    /**
     * Creates new form ItemDialog
     */
    public ItemDialog(java.awt.Frame parent, boolean modal, Handler handler, ItemTO item, OnFormularioResult listener) {
        super(parent, modal);
        this.listener = listener;
        this.handler = handler;
        novo = item == null;
        initComponents();
        preencherDadosInciais(item);
        configurarHandler();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextPane();
        btnCancelarItem = new javax.swing.JToggleButton();
        btnGravarItem = new javax.swing.JToggleButton();
        txtPreco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jlPreco = new javax.swing.JLabel();
        jlNomeItem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(txtDescricao);

        btnCancelarItem.setText("Cancelar");
        btnCancelarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarItemActionPerformed(evt);
            }
        });

        btnGravarItem.setText("Gravar");
        btnGravarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarItemActionPerformed(evt);
            }
        });

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        jLabel1.setText("Descrição: ");

        jlPreco.setText("* Preço:");

        jlNomeItem.setText("* Nome:");

        jLabel2.setText("*Código:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGravarItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarItem))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jlPreco)
                            .addGap(18, 18, 18)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jlNomeItem)
                            .addGap(18, 18, 18)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarItem)
                    .addComponent(btnCancelarItem)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarItemActionPerformed
        handler.limparNotificacoes();
        boolean podeFechar = listener.onCloseDialog(OnFormularioResult.Botao.OK, getDados(), novo);
        if (podeFechar) {
            dispose();
        }
    }//GEN-LAST:event_btnGravarItemActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void btnCancelarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarItemActionPerformed
        if (listener != null) {
            boolean podeFechar = listener.onCloseDialog(OnFormularioResult.Botao.CANCELAR, null, novo);
            if (podeFechar) {
                dispose();
            }
        }
    }//GEN-LAST:event_btnCancelarItemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelarItem;
    private javax.swing.JToggleButton btnGravarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlNomeItem;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextPane txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables

    @Override
    public void preencherDadosInciais(Object objeto) {
        if (objeto != null && objeto instanceof ItemTO) {
            ItemTO i = (ItemTO) objeto;
            idItem = i.getId();
            txtNome.setText(i.getNome());
            txtDescricao.setText(i.getDescricao());
            txtPreco.setText(i.getPreco());
            txtCodigo.setText(i.getCodigo());

        }
    }

    @Override
    public void configurarHandler() {
        handler.add(ItemValidacao.CHAVE_CAMPO_ITEM_NOME, txtNome);
        handler.add(ItemValidacao.CHAVE_CAMPO_ITEM_CODIGO, txtCodigo);
        handler.add(ItemValidacao.CHAVE_CAMPO_ITEM_DESCRICAO, txtDescricao);
        handler.add(ItemValidacao.CHAVE_CAMPO_ITEM_PRECO, txtPreco);

    }

    @Override
    public ItemTO getDados() {

        ItemTO i = new ItemTO();
        if (!novo) {
            i.setId(idItem);
        }
        i.setNome(txtNome.getText());
        i.setCodigo(txtCodigo.getText());
        i.setPreco(txtPreco.getText());
        i.setDescricao(txtDescricao.getText());

        return i;
    }
}
