/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unioeste.sisra.win.tela.mesa;

import br.unioeste.sisra.win.tela.item.*;
import br.unioeste.sisra.controle.validacao.Validacao;
import br.unioeste.sisra.modelo.to.ItemTO;
import br.unioeste.sisra.modelo.to.MesaTO;
import br.unioeste.sisra.win.componente.Handler;
import br.unioeste.sisra.win.componente.SimpleTableModel;
import br.unioeste.sisra.win.tela.funcionario.FuncionarioActivity;
import java.util.ArrayList;

/**
 *
 * @author Charlinho
 */
public class MesaListagem extends javax.swing.JPanel {

    SimpleTableModel tblItemModel;
    private final MesaActivity activity;
    private final Handler handler;

    /**
     * Creates new form ItemListagem
     */
    public MesaListagem(MesaActivity activity, Handler handler) {
        this.activity = activity;
        this.handler = handler;

        initTabelaItems();
        initComponents();
        configurarHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblItem.setModel(tblItemModel);
        jScrollPane1.setViewportView(tblItem);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome"}));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(txtBusca)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(btnBuscar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnExcluir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnEditar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(btnNovo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBuscar)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 248, Short.MAX_VALUE)
                        .add(btnNovo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnEditar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnExcluir))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
         activity.abrirFormularioMesa(null);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
           try {
            activity.buscarMesa(txtBusca.getText(), FuncionarioActivity.Campo.ID);
        } catch (Exception e) {
            handler.handle(e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String pk = (String) tblItemModel.getValueAt(tblItem.getSelectedRow(), FuncionarioActivity.Campo.ID);
            activity.editarMesa(pk);
        } catch (Exception ex) {
            handler.handle(ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            String pk = (String) tblItemModel.getValueAt(tblItem.getSelectedRow(), FuncionarioActivity.Campo.ID);
            String nome = (String) tblItemModel.getValueAt(tblItem.getSelectedRow(), FuncionarioActivity.Campo.NOME);
            activity.excluirMesa(pk, nome);
        } catch (Exception ex) {
            handler.handle(ex);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

    private void initTabelaItems() {
        String[] colunas = new String[4];
        ArrayList dadosTabela = new ArrayList();

        colunas[MesaActivity.Campo.ID] = "ID";
        colunas[MesaActivity.Campo.DESCRICAO] = "Descrição";
        colunas[MesaActivity.Campo.OBS] = "Obs";
        colunas[MesaActivity.Campo.STATUS] = "Status";


        tblItemModel = new SimpleTableModel(dadosTabela, colunas);
    }

    public void exibeBusca(MesaTO[] mesas) {
        tblItemModel.removeAllElements();

        for (MesaTO f : mesas) {
            tblItemModel.addRow(toArrayString(f));
        }
        tblItem.updateUI();
    }

    private void configurarHandler() {
        handler.add(Validacao.CHAVE_CAMPO_BUSCA, txtBusca);
    }

    public void atualizaMesa(MesaTO f) {
        final int idLinha = tblItemModel.getIdLinha(MesaActivity.Campo.ID, String.valueOf(f.getId()));
        if (idLinha >= 0) {
            tblItemModel.editarRow(idLinha, toArrayString(f));
        }
        tblItem.updateUI();
    }

    public void remover(String pk) {
        tblItemModel.removeRow(pk, ItemActivity.Campo.ID);
        tblItem.updateUI();
    }

    private String[] toArrayString(MesaTO i) {
        String[] linha = new String[4];
        linha[MesaActivity.Campo.ID] = i.getId() == null ? "" : String.valueOf(i.getId());
        linha[MesaActivity.Campo.DESCRICAO] = i.getDescricao();
        linha[MesaActivity.Campo.OBS] = i.getObs();
        linha[MesaActivity.Campo.STATUS] = i.getStatus();
        return linha;
    }
}
