/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unioeste.sisra.win.tela.funcionario;

import br.unioeste.sisra.controle.validacao.Validacao;
import br.unioeste.sisra.modelo.to.FuncionarioTO;
import br.unioeste.sisra.win.componente.Handler;
import br.unioeste.sisra.win.componente.SimpleTableModel;
import java.util.ArrayList;
import javax.swing.JTable;

/**
 *
 * @author Charlinho
 */
public class FuncionarioListagem extends javax.swing.JPanel {

    SimpleTableModel tblFuncionariosModel;
    private  FuncionarioActivity activity;
    private  Handler handler;

    /**
     * Creates new form FuncionarioListagem
     */
    public FuncionarioListagem(FuncionarioActivity activity, Handler handler) {
        this.activity = activity;
        this.handler = handler;

        initTabelaFuncionarios();
        initComponents();
        configurarHandler();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblFuncionarios.setModel(tblFuncionariosModel);
        jScrollPane1.setViewportView(tblFuncionarios);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome"}));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(txtBusca)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(btnBuscar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnExcluir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnEditar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(btnNovo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtBusca, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBuscar)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(btnNovo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnEditar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnExcluir))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        activity.abrirFormularioFuncionario(null);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            activity.buscarFuncionario(txtBusca.getText(), FuncionarioActivity.Campo.ID);
        } catch (Exception e) {
            handler.handle(e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String pk = (String) tblFuncionariosModel.getValueAt(tblFuncionarios.getSelectedRow(), FuncionarioActivity.Campo.ID);
            activity.editarFuncionario(pk);
        } catch (Exception ex) {
            handler.handle(ex);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            String pk = (String) tblFuncionariosModel.getValueAt(tblFuncionarios.getSelectedRow(), FuncionarioActivity.Campo.ID);
            String nome = (String) tblFuncionariosModel.getValueAt(tblFuncionarios.getSelectedRow(), FuncionarioActivity.Campo.NOME);
            activity.excluirFuncionario(pk, nome);
        } catch (Exception ex) {
            handler.handle(ex);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

    private void initTabelaFuncionarios() {
        String[] colunas = new String[4];
        ArrayList dadosTabela = new ArrayList();

        colunas[FuncionarioActivity.Campo.ID] = "Id";
        colunas[FuncionarioActivity.Campo.NOME] = "Nome";
        colunas[FuncionarioActivity.Campo.CPF] = "CPF";
        colunas[FuncionarioActivity.Campo.RG] = "RG";


        tblFuncionariosModel = new SimpleTableModel(dadosTabela, colunas);
    }

    public void exibeBusca(FuncionarioTO[] funcionarios) {
        tblFuncionariosModel.removeAllElements();

        for (FuncionarioTO f : funcionarios) {
            tblFuncionariosModel.addRow(toArrayString(f));
        }
        tblFuncionarios.updateUI();
    }

    private void configurarHandler() {
        handler.add(Validacao.CHAVE_CAMPO_BUSCA, txtBusca);
    }

    public void atualizaFuncionario(FuncionarioTO f) {
        final int idLinha = tblFuncionariosModel.getIdLinha(FuncionarioActivity.Campo.ID, String.valueOf(f.getId()));
        if (idLinha >= 0) {
            tblFuncionariosModel.editarRow(idLinha, toArrayString(f));
        }
        tblFuncionarios.updateUI();
    }

    public void remover(String pk) {
        tblFuncionariosModel.removeRow(pk, FuncionarioActivity.Campo.ID);
        tblFuncionarios.updateUI();
    }

    private String[] toArrayString(FuncionarioTO f) {
        String[] linha = new String[5];
        linha[FuncionarioActivity.Campo.ID] = f.getId() == null ? "" : String.valueOf(f.getId());
        linha[FuncionarioActivity.Campo.NOME] = f.getNome();
        linha[FuncionarioActivity.Campo.CPF] = f.getCpf();
        linha[FuncionarioActivity.Campo.RG] = f.getRg();
        return linha;
    }
}
